name: KreditSch
description: "KreditSch"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  visibility_detector: ^0.4.0+2
  supabase_flutter: ^2.3.4
  file_picker: ^10.3.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  intl: ^0.20.2
  pdf: ^3.10.7
  printing: ^5.12.0
  http: ^1.2.0
  image_picker: ^1.2.1
  go_router: ^17.0.1
  provider: ^6.1.5+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0



flutter:


  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/pdf/
    - assets/fonts/
