name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code
      - uses: actions/checkout@v4

      # Installer Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.6' # ou la version que tu utilises

      # Installer les dépendances Flutter
      - run: flutter pub get

      # Build Flutter Web
      - run: flutter build web --release

      # Déployer sur Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LOAN_WEB_APP_B5697 }}
          channelId: live
          projectId: loan-web-app-b5697